---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: middleware
  labels:
    app: rabbitmq01
spec:
  ports:
  - port: 15672
    name: http
    nodePort: 15672
  - port: 5672
    name: amqp
    nodePort: 5672
  selector:
    app: rabbitmq
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: middleware
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
  - port: 5672
    name: amqp
  selector:
    app: rabbitmq
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq01
  namespace: middleware
spec:
  serviceName: rabbitmq
  replicas: 2
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: rabbitmq
      containers:
      - name: rabbitmq
        image: duruo850/rabbitmq:3.11.11-management-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5672
          name: amqp
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "system"
          - name: RABBITMQ_DEFAULT_PASS
            value: "rbmqu0101081710"
        volumeMounts:
        - name: rabbitmq-volume
          mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-volume
          hostPath:
            path: /data/kubernetes/rabbitmq_server-3.6.2
